### ISSUE TITLE
2Keys detector fails to run

### ISSUE THREAD

**Issue by codemicro** [Gum-Joe/2Keys#18]
The 2Keys detector software on the Pi installs successfully, however the command is not found when I try to run it. Below is the output of pip:
```

pi@keybServerPi:~ $ sudo pip3 install 2keys
Collecting 2keys
  Downloading https://files.pythonhosted.org/packages/91/51/14ef261ad3393ac2be0f857c3589bd585f23eefbc0166f5d02fb927e6fa3/2Keys-0.3.6-py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 1.1MB/s
Collecting aiohttp (from 2keys)
  Downloading https://www.piwheels.org/simple/aiohttp/aiohttp-3.5.4-cp35-cp35m-linux_armv7l.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 217kB/s
Collecting colorful (from 2keys)
  Downloading https://files.pythonhosted.org/packages/a1/d7/59181df2dadf1234afddc93f1b7d965e1614423bb6a87845ea49f841c88a/colorful-0.5.0-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 741kB/s
Collecting pystache (from 2keys)
  Downloading https://www.piwheels.org/simple/pystache/pystache-0.5.4-py3-none-any.whl (89kB)
    100% |████████████████████████████████| 92kB 1.2MB/s
Collecting aiofiles (from 2keys)
  Downloading https://files.pythonhosted.org/packages/cf/f2/a67a23bc0bb61d88f82aa7fb84a2fb5f278becfbdc038c5cbb36c31feaf1/aiofiles-0.4.0-py3-none-any.whl
Collecting requests (from 2keys)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 1.3MB/s
Requirement already satisfied: pyyaml in /usr/local/lib/python3.5/dist-packages/PyYAML-5.1-py3.5-linux-armv7l.egg (from 2keys)
Collecting evdev (from 2keys)
  Downloading https://files.pythonhosted.org/packages/fe/6e/3fa84a43571dec4d00dc26befccc9867b6b3263651531cbc1345f718860f/evdev-1.2.0.tar.gz
Collecting yarl<2.0,>=1.0 (from aiohttp->2keys)
  Downloading https://www.piwheels.org/simple/yarl/yarl-1.3.0-cp35-cp35m-linux_armv7l.whl (227kB)
    100% |████████████████████████████████| 235kB 699kB/s
Collecting chardet<4.0,>=2.0 (from aiohttp->2keys)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.0MB/s
Collecting idna-ssl>=1.0; python_version < "3.7" (from aiohttp->2keys)
  Downloading https://www.piwheels.org/simple/idna-ssl/idna_ssl-1.1.0-py3-none-any.whl
Collecting typing-extensions>=3.6.5; python_version < "3.7" (from aiohttp->2keys)
  Downloading https://files.pythonhosted.org/packages/27/aa/bd1442cfb0224da1b671ab334d3b0a4302e4161ea916e28904ff9618d471/typing_extensions-3.7.4-py3-none-any.whl
Collecting attrs>=17.3.0 (from aiohttp->2keys)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting multidict<5.0,>=4.0 (from aiohttp->2keys)
  Downloading https://www.piwheels.org/simple/multidict/multidict-4.5.2-cp35-cp35m-linux_armv7l.whl (301kB)
    100% |████████████████████████████████| 307kB 444kB/s
Collecting async-timeout<4.0,>=3.0 (from aiohttp->2keys)
  Downloading https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->2keys)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 1.2MB/s
Collecting certifi>=2017.4.17 (from requests->2keys)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl (157kB)
    100% |████████████████████████████████| 163kB 828kB/s
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->2keys)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 1.1MB/s
Building wheels for collected packages: evdev
  Running setup.py bdist_wheel for evdev ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-41ieqi48/evdev/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp7azi3ty7pip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: invalid command 'bdist_wheel'

  ----------------------------------------
  Failed building wheel for evdev
  Running setup.py clean for evdev
Failed to build evdev
Installing collected packages: multidict, idna, yarl, chardet, idna-ssl, typing-extensions, attrs, async-timeout, aiohttp, colorful, pystache, aiofiles, certifi, urllib3, requests, evdev, 2keys
  Found existing installation: idna 2.2
    Not uninstalling idna at /usr/lib/python3/dist-packages, outside environment /usr
  Running setup.py install for evdev ... done
Successfully installed 2keys-0.3.6 aiofiles-0.4.0 aiohttp-3.5.4 async-timeout-3.0.1 attrs-19.1.0 certifi-2019.6.16 chardet-3.0.4 colorful-0.5.0 evdev-1.2.0 idna-2.8 idna-ssl-1.1.0 multidict-4.5.2 pystache-0.5.4 requests-2.22.0 typing-extensions-3.7.4 urllib3-1.25.3 yarl-1.3.0
```
which seemed fine.

Running `sudo 2Keys --version` results in this:
```
pi@keybServerPi:~/2keys $ sudo 2Keys --version
Traceback (most recent call last):
  File "/usr/local/bin/2Keys", line 7, in <module>
    from twokeys.cli import cli
  File "/usr/local/lib/python3.5/dist-packages/twokeys/__init__.py", line 19, in <module>
    from .cli import cli
  File "/usr/local/lib/python3.5/dist-packages/twokeys/cli/__init__.py", line 19, in <module>
    from .cli import cli
  File "/usr/local/lib/python3.5/dist-packages/twokeys/cli/cli.py", line 22, in <module>
    import click
ImportError: No module named 'click'
```

**Comment by Gum-Joe** [comment]
Try running `which pip3`

**Comment by codemicro** [comment]
Nope, that works. `/usr/bin/pip3`

**Comment by Gum-Joe** [comment]
Could you see if running a small python 3 scripts with `import twokeys` works please?

**Comment by codemicro** [comment]
It didn't work.
```
pi@keybServerPi:~/2keys $ sudo python3 test2k.py
Graceful death - module didn't import
```

**Comment by Gum-Joe** [comment]
Ok so I think I've figured out the issue: It appears to be the `required.txt` file, that contains the list of all dependencies, doesn't contain `click`.  I'm going to go in and quickly check & edit this file now.

**Comment by codemicro** [comment]
Oh - I should have seen that when I looked at the log. I installed it and all is dandy.
```
pi@keybServerPi:~/2keys $ sudo 2Keys --version
Usage: 2Keys [OPTIONS] COMMAND [ARGS]...
Try "2Keys --help" for help.

Error: no such option: --version
```

**Comment by Gum-Joe** [comment]
Yay!

**Comment by Gum-Joe** [comment]
Ok so it appears that only `click` was missing

**Comment by Gum-Joe** [comment]
Just 0.3.7 with click hopefully preinstalled to PyPI.  Might take a little while until you can download it, but its pushed.
