### ISSUE TITLE
config.yml changes are not syncing to the detector

### ISSUE THREAD

**Issue by codemicro** [Gum-Joe/2Keys#20]
After making a change in the `config.yml` file on the server in the project root, and then running `2Keys sync`, no change occurs in the detector's `config.yml`. Running `sudo 2Keys config-update` yeilds 
```
pi@keybServerPi:~/2keys $ sudo 2Keys config-update
Usage: 2Keys [OPTIONS] COMMAND [ARGS]...
Try "2Keys --help" for help.

Error: No such command "config-update".
```

**Comment by Gum-Joe** [comment]
The correct command is `2Keys sync`

**Comment by codemicro** [comment]
```
pi@keybServerPi:~/2keys $ sudo 2Keys sync
cli warn This will overwrite the copy of the config on the detector. Proceed? [Y/n]
y
sync info Syncing config...
/usr/local/lib/python3.5/dist-packages/twokeys/util/config.py:25: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(config_file.read())
sync debug GET http://192.168.5.252:9090/api/get/config
sync err Couldn't estanblish a connection to the server.
sync err Please check your internet connection.
```
I know my internet is working... because.... well, SSH? :D

**Comment by Gum-Joe** [comment]
The 2Keys server is definitely running?
And the IP definitely correct?
It may be the server also crashed. Logs are available server side in the `.2Keys` folder

**Comment by codemicro** [comment]
It appears the server crashed - here's the log if you're interested.
```
Wed, 26 Jun 2019 17:24:26 GMT express:router:route new '/get/config'
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/get/config'
Wed, 26 Jun 2019 17:24:26 GMT express:router:route get '/get/config'
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/'
Wed, 26 Jun 2019 17:24:26 GMT express:router:route new '/post/trigger'
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/post/trigger'
Wed, 26 Jun 2019 17:24:26 GMT express:router:route post '/post/trigger'
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/'
Wed, 26 Jun 2019 17:24:26 GMT express:router:route new '/post/update-keyboard-path'
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/post/update-keyboard-path'
Wed, 26 Jun 2019 17:24:26 GMT express:router:route post '/post/update-keyboard-path'
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/'
Wed, 26 Jun 2019 17:24:26 GMT express:application set "x-powered-by" to true
Wed, 26 Jun 2019 17:24:26 GMT express:application set "etag" to 'weak'
Wed, 26 Jun 2019 17:24:26 GMT express:application set "etag fn" to [Function: generateETag]
Wed, 26 Jun 2019 17:24:26 GMT express:application set "env" to 'development'
Wed, 26 Jun 2019 17:24:26 GMT express:application set "query parser" to 'extended'
Wed, 26 Jun 2019 17:24:26 GMT express:application set "query parser fn" to [Function: parseExtendedQueryString]
Wed, 26 Jun 2019 17:24:26 GMT express:application set "subdomain offset" to 2
Wed, 26 Jun 2019 17:24:26 GMT express:application set "trust proxy" to false
Wed, 26 Jun 2019 17:24:26 GMT express:application set "trust proxy fn" to [Function: trustNone]
Wed, 26 Jun 2019 17:24:26 GMT express:application booting in development mode
Wed, 26 Jun 2019 17:24:26 GMT express:application set "view" to [Function: View]
Wed, 26 Jun 2019 17:24:26 GMT express:application set "views" to 'c:\\2keys\\views'
Wed, 26 Jun 2019 17:24:26 GMT express:application set "jsonp callback name" to 'callback'
Wed, 26 Jun 2019 17:24:26 GMT express:router use '/' query
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/'
Wed, 26 Jun 2019 17:24:26 GMT express:router use '/' expressInit
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/'
Wed, 26 Jun 2019 17:24:26 GMT express:router use '/' jsonParser
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/'
Wed, 26 Jun 2019 17:24:26 GMT express:router use '/api' router
Wed, 26 Jun 2019 17:24:26 GMT express:router:layer new '/api'
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9090
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Function.listen (c:\2keys\server\node_modules\express\lib\application.js:618:24)
    at server (c:\2keys\server\lib\index.js:39:9)
    at Object.yargs.command [as handler] (c:\2keys\server\bin\2Keys:51:5)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
The sync command ran successfully.

**Comment by Gum-Joe** [comment]
Ok well that means something else is listening on port 9090, but if the sync command ran successfully, the 2Keys server was probably already running on 9090.
